Syncing Keepass DBs now allows scoping to just 1

diff --git a/bin/sync-keepass-databases b/bin/sync-keepass-databases
--- a/bin/sync-keepass-databases
+++ b/bin/sync-keepass-databases
@@ -4,12 +4,27 @@ PATH="/usr/local/bin:$PATH"
 
 if [ ! -e "${HOME}/Documents/Auth" ]; then exit 0; fi
 
-for db in "${HOME}"/Documents/Auth/*.kdbx; do
-  if [ ! -e "$db" ] || [[ "$db" == *.old.kdbx ]]; then continue; fi
+if [ $# -gt 0 ]; then
+  db="${HOME}/Documents/Auth/${1}.kdbx"
   db_name=$(basename "${db}")
 
-  rclone copy "$db" dropbox:SharedAuth/ --update
-  rclone copy dropbox:SharedAuth/"${db_name}" "${HOME}/Documents/Auth/" --update
+  if [ -e "$db" ]; then
+    rclone copy "$db" dropbox:SharedAuth/ --update
+    rclone copy dropbox:SharedAuth/"${db_name}" "${HOME}/Documents/Auth/" --update
 
-  printf 'Synced Keepass Database %s\n' "$db_name"
-done
+    printf 'Synced Keepass Database %s\n' "$db_name"
+  else
+    printf 'ERROR: No such Keepass Database %s\n' "$db_name" 1>&2
+    exit 1
+  fi
+else
+  for db in "${HOME}"/Documents/Auth/*.kdbx; do
+    if [ ! -e "$db" ] || [[ "$db" == *.old.kdbx ]]; then continue; fi
+    db_name=$(basename "${db}")
+
+    rclone copy "$db" dropbox:SharedAuth/ --update
+    rclone copy dropbox:SharedAuth/"${db_name}" "${HOME}/Documents/Auth/" --update
+
+    printf 'Synced Keepass Database %s\n' "$db_name"
+  done
+fi
