Cleans up custom executables in PATH

diff --git a/local/bin/dbuild b/local/bin/dbuild
--- a/local/bin/dbuild
+++ b/local/bin/dbuild
@@ -1,7 +1,7 @@
 #!/bin/sh
 
 if [ $# -eq 0 ]; then
-  echo 'Missing name for docker container' >&2
+  printf 'Missing name for docker container\n' >&2
   exit 1
 fi
 
diff --git a/local/bin/dconsole b/local/bin/dconsole
--- a/local/bin/dconsole
+++ b/local/bin/dconsole
@@ -1,16 +1,14 @@
-#!/bin/sh
+#!/usr/bin/env bash
+set -euo pipefail
 
 if [ $# -eq 0 ]; then
-  echo 'Missing name for docker container' >&2
+  printf 'Missing name for docker container' >&2
   exit 1
 fi
 
 image="${1}"
 shell_type="${2:-sh}"
-mkdir -p "$PWD/from_docker"
+mkdir -p "./from_docker"
+trap 'rmdir "./from_docker" 2>/dev/null' EXIT
+
 docker run --entrypoint='' --rm -v "$PWD/from_docker:/out" -it "$image" "$shell_type"
-last_exit=$?
-
-rmdir "$PWD/from_docker" 2>/dev/null || true
-
-exit $last_exit
diff --git a/local/bin/git-reauthor b/local/bin/git-reauthor
--- a/local/bin/git-reauthor
+++ b/local/bin/git-reauthor
@@ -1,11 +1,10 @@
 #!/usr/bin/env bash
+set -euo pipefail
 
 
 init_variables() {
-  COMMAND=${0#*-}
+  COMMAND="${0#*-}"
 
-  CONFIG=false
-  ALL=false
   unset OLD_EMAIL
   unset CORRECT_EMAIL
   unset CORRECT_NAME
@@ -18,21 +17,18 @@ usage() {
 usage: git ${COMMAND} [<options>]
 
 Options
-    -a, --all                     rewrite all identities in commits and tags
-    -c, --use-config              define correct values from user Git config
-    -e, --correct-email  <email>  define the correct email to set
-    -n, --correct-name   <name>   define the correct name to set
+    -e, --correct-email  <email>  define the correct email to set (default: value of \`git config user.email\`)
+    -n, --correct-name   <name>   define the correct name to set (default: value of \`git config user.name\`)
     -o, --old-email      <email>  rewrite identities matching old email in commits and tags
     -t, --type           <id>     define the type of identities affected by the rewrite
-                                  author, committer, both (default)
+                                  'author', 'committer', 'both' (default: 'both')
 EOF
 }
 
 
 error() {
-  if [[ -n "$1" ]]; then
-    local msg=$( echo "error: $1" | sed 's/\\n/\\n       /g' )
-    echo -e "${msg}" >&2
+  if [ -n "${1:-}" ]; then
+    printf 'error: %s\n' "$1" >&2
   fi
   usage
   exit 1
@@ -40,30 +36,27 @@ error() {
 
 
 reauthor() {
-  local author='
-    if ${ALL} || [ "${GIT_AUTHOR_EMAIL}" = "${OLD_EMAIL}" ]; then
+  local author committer filter
+  author='
+    if [ "${GIT_AUTHOR_EMAIL}" = "${OLD_EMAIL}" ]; then
       [ -z "${CORRECT_EMAIL+x}" ] || export GIT_AUTHOR_EMAIL="${CORRECT_EMAIL}"
       [ -z "${CORRECT_NAME+x}" ] || export GIT_AUTHOR_NAME="${CORRECT_NAME}"
     fi
   '
-  local committer='
-    if ${ALL} || [ "${GIT_COMMITTER_EMAIL}" = "${OLD_EMAIL}" ]; then
+  committer='
+    if [ "${GIT_COMMITTER_EMAIL}" = "${OLD_EMAIL}" ]; then
       [ -z "${CORRECT_EMAIL+x}" ] || export GIT_COMMITTER_EMAIL="${CORRECT_EMAIL}"
       [ -z "${CORRECT_NAME+x}" ] || export GIT_COMMITTER_NAME="${CORRECT_NAME}"
     fi
   '
-  local filter
 
-  case "${TYPE}" in
+  case "${TYPE:-both}" in
     author) filter="${author}" ;;
     committer) filter="${committer}" ;;
     both) filter="${author} ${committer}" ;;
   esac
 
-  export ALL
-  export OLD_EMAIL
-  export CORRECT_EMAIL
-  export CORRECT_NAME
+  export OLD_EMAIL CORRECT_EMAIL CORRECT_NAME
 
   git filter-branch --force --env-filter "${filter}" \
   --tag-name-filter cat -- --branches --tags
@@ -71,50 +64,51 @@ reauthor() {
 
 
 parse_options() {
-  while [[ "$#" -gt 0 ]]; do
-    case "$1" in
-      --all|-a)
-        ALL=true
-        shift
-        ;;
+  while [ "$#" -gt 0 ]; do
+    case "${1}" in
       --correct-email|-e)
-        [[ -n "${2+x}" ]] || error 'Missing correct-email value'
+        if [ -n "${2+x}" ]; then
+          error 'Missing value for `--correct-email` parameter'
+        fi
         CORRECT_EMAIL="$2"
         shift 2
         ;;
-      -h)
+      --help|-h)
         usage
         exit 0
         ;;
       --correct-name|-n)
-        [[ -n "${2+x}" ]] || error 'Missing correct-name value'
+        if [ -n "${2+x}" ]; then
+          error 'Missing value for `--correct-name` parameter'
+        fi
         CORRECT_NAME="$2"
         shift 2
         ;;
       --old-email|-o)
-        [[ -n "${2+x}" ]] || error 'Missing old-email value'
+        if [ -n "${2+x}" ]; then
+          error 'Missing value for `--old-email` parameter'
+        fi
         OLD_EMAIL="$2"
         shift 2
         ;;
       --type|-t)
-        [[ -n "${2+x}" ]] || error 'Missing type value'
+        if [ -n "${2+x}" ]; then
+          error 'Missing value for `--type` parameter'
+        fi
         TYPE="$2"
         shift 2
         ;;
-      --use-config|-c)
-        CONFIG=true
-        shift
-        ;;
       *)
-        error "invalid option '$1'"
+        error "invalid option \`$1\`"
         ;;
     esac
   done
 
-  if ${CONFIG}; then
-    # use config values if not explicitly already defined
-    [[ -n "${CORRECT_EMAIL+x}" ]] || CORRECT_EMAIL=$( git config user.email )
-    [[ -n "${CORRECT_NAME+x}" ]] || CORRECT_NAME=$( git config user.name )
+  if [ -z "${CORRECT_EMAIL:-}" ]; then
+    CORRECT_EMAIL="$(git config user.email)"
+  fi
+  if [ -z "${CORRECT_NAME:-}" ]; then
+    CORRECT_NAME="$(git config user.name)"
   fi
 }
 
@@ -154,7 +148,12 @@ validate_options() {
 }
 
 
-init_variables
+COMMAND="${0#*-}"
+unset OLD_EMAIL
+unset CORRECT_EMAIL
+unset CORRECT_NAME
+TYPE='both'
+
 parse_options "$@"
 validate_options
 
