Uses jabba for java version switching in direnv

diff --git a/config/direnv/direnvrc b/config/direnv/direnvrc
--- a/config/direnv/direnvrc
+++ b/config/direnv/direnvrc
@@ -103,3 +103,25 @@ use_customized_vim() {
     path_add EXTRA_VIM "$extravim"
   fi
 }
+
+use_java() {
+  if [ ! -e "${HOME}/.jabba/jabba.sh" ]; then
+    log_error 'Not found: jabba. Please install from https://github.com/shyiko/jabba and then run `direnv reload`'
+    exit 1
+  fi
+
+  . "${HOME}/.jabba/jabba.sh"
+
+  if [ -n "${1:-}" ]; then
+    jabba use "${1}"
+  elif [ -z "${1:-}" ] && [ -n "$(jabba alias default)" ]; then
+    jabba use default
+  else
+    log_error 'No "default" java found. Please set it with `jabba alias default {version}`'
+  fi
+  hash -r
+
+  # Not needed since direnv reverts it for us, so we're
+  # unsetting it to reduce noise in the direnv diff
+  unset JAVA_HOME_BEFORE_JABBA
+}
