Better messaging for vim/neovim plugin install scripts

diff --git a/hooks/post-up/1_neovim b/hooks/post-up/1_neovim
--- a/hooks/post-up/1_neovim
+++ b/hooks/post-up/1_neovim
@@ -1,6 +1,11 @@
 #!/bin/bash
 set -e
 
+if ! command -v nvim &>/dev/null; then
+  # NeoVim is not installed, so we don't need to install the plugins
+  exit 0
+fi
+
 cat <<MSG
 --------------------
 >>  NeoVim plugins
@@ -44,15 +49,24 @@ if [ ! -e "$HOME"/.config/nvim/autoload/plug.vim ]; then
 fi
 
 if [ -e "$HOME"/.config/nvim/bundles.vim ]; then
-  if __verify_base_and_local_md5 "$HOME"/.config/nvim/bundles.vim; then
-    echo "NeoVim bundles are being updated..."
-    command nvim -u "$HOME"/.config/nvim/bundles.vim +PlugUpdate +'PlugClean!' +qall </dev/null &>/dev/null
+  if ! __verify_base_and_local_md5 "$HOME"/.config/nvim/bundles.vim; then
+    printf 'NeoVim bundles are being installed... '
+    if command nvim -u "$HOME"/.config/nvim/bundles.vim +'PlugInstall' +'qall' </dev/null &>/dev/null; then
+      printf 'Done\n'
+      __generate_base_and_local_md5 "$HOME"/.config/nvim/bundles.vim
+    else
+      printf 'ERROR\n'
+      printf 'Encountered an error when running `%s`\n' "nvim +'PlugInstall'" >&2
+    fi
+  fi
+
+  printf 'NeoVim bundles are being updated... '
+  if command nvim -u "$HOME"/.config/nvim/bundles.vim +'PlugUpdate' +'PlugClean!' +'qall' </dev/null &>/dev/null; then
+    printf 'Done\n'
+    __generate_base_and_local_md5 "$HOME"/.config/nvim/bundles.vim
   else
-    echo "NeoVim bundles are being updated..."
-    command nvim -u "$HOME"/.config/nvim/bundles.vim +PlugInstall +PlugUpdate +'PlugClean!' +qall </dev/null &>/dev/null \
-      && __generate_base_and_local_md5 "$HOME"/.config/nvim/bundles.vim \
-      && echo "NeoVim bundles were updated" \
-      || echo "ERROR: encountered an error when running \`nvim +'PlugInstall'\`" >&2
+    printf 'ERROR\n'
+    printf 'Encountered an error when running `%s`\n' "nvim +'PlugUpdate'" >&2
   fi
 fi
 
diff --git a/hooks/post-up/1_vim b/hooks/post-up/1_vim
--- a/hooks/post-up/1_vim
+++ b/hooks/post-up/1_vim
@@ -1,6 +1,11 @@
 #!/bin/bash
 set -e
 
+if ! command -v vim &>/dev/null; then
+  # Vim is not installed, so we don't need to install the plugins
+  exit 0
+fi
+
 cat <<MSG
 --------------------
 >>  Vim plugins
@@ -45,15 +50,23 @@ if [ ! -e "$HOME"/.vim/autoload/plug.vim ]; then
 fi
 
 if [ -e "$HOME"/.vimrc.bundles ]; then
-  if __verify_base_and_local_md5 "$HOME"/.vimrc.bundles; then
-    echo "Vim bundles are being updated..."
-    command vim -u "$HOME"/.vimrc.bundles +PlugUpdate +'PlugClean!' +qall </dev/null &>/dev/null
+  if ! __verify_base_and_local_md5 "$HOME"/.vimrc.bundles; then
+    printf 'Vim bundles are being installed... '
+    if command vim -u "$HOME"/.vimrc.bundles +'PlugInstall' +'qall' </dev/null &>/dev/null; then
+      printf 'Done\n'
+      __generate_base_and_local_md5 "$HOME"/.vimrc.bundles
+    else
+      printf 'ERROR\n'
+      printf 'Encountered an error when running `%s`' "vim +'PlugInstall'" >&2
+    fi
+  fi
+
+  printf 'Vim bundles are being updated... '
+  if command vim -u "$HOME"/.vimrc.bundles +'PlugUpdate' +'PlugClean!' +'qall' </dev/null &>/dev/null; then
+    printf 'Done\n'
   else
-    echo "Vim bundles are being updated..."
-    command vim -u "$HOME"/.vimrc.bundles +PlugInstall +PlugUpdate +'PlugClean!' +qall </dev/null &>/dev/null \
-      && __generate_base_and_local_md5 "$HOME"/.vimrc.bundles \
-      && echo "Vim bundles were updated" \
-      || echo "ERROR: encountered an error when running \`vim +'PlugInstall'\`" >&2
+    printf 'ERROR\n'
+    printf 'Encountered an error when running `%s`' "vim +'PlugUpdate'" >&2
   fi
 fi
 
